# Generated by Django 4.2.15 on 2024-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_logintable_status_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Inactive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('Pending', 'pending'), ('Shop', 'shop'), ('USER', 'user'), ('Admin', 'admin')], max_length=20, null=True),
        ),
    ]
