# Generated by Django 4.2.15 on 2024-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('Pending', 'pending'), ('USER', 'user'), ('Shop', 'shop'), ('Admin', 'admin')], max_length=20, null=True),
        ),
    ]
