# Generated by Django 4.2.15 on 2024-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0019_alter_logintable_status_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'admin'), ('Shop', 'shop'), ('Pending', 'pending'), ('USER', 'user')], max_length=20, null=True),
        ),
    ]
