# Generated by Django 4.2.15 on 2024-11-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0020_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Inactive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('Pending', 'pending'), ('USER', 'user'), ('Admin', 'admin'), ('Shop', 'shop')], max_length=20, null=True),
        ),
    ]
