# Generated by Django 4.2.15 on 2024-11-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0021_alter_logintable_status_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('Pending', 'pending'), ('Admin', 'admin'), ('Shop', 'shop'), ('USER', 'user')], max_length=20, null=True),
        ),
    ]
