# Generated by Django 4.2.15 on 2024-11-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_product_table_shoplid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='Categorytype',
        ),
        migrations.RemoveField(
            model_name='product_table',
            name='Category',
        ),
        migrations.AddField(
            model_name='product_table',
            name='Categorytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.category'),
        ),
    ]
