# Generated by Django 4.2.15 on 2024-11-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_rename_category_category_categorytype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_review_table',
            name='SHOPLID',
        ),
        migrations.AddField(
            model_name='rating_review_table',
            name='PRODUCTID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.product_table'),
        ),
    ]
