# Generated by Django 4.2.15 on 2024-11-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_remove_rating_review_table_shoplid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_table',
            name='SHOPLID',
        ),
    ]
