# Generated by Django 4.2.15 on 2024-11-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_remove_complaint_table_shoplid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='Complaint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
