# Generated by Django 4.2.15 on 2024-11-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_complaint_table_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
