# Generated by Django 4.2.15 on 2024-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_product_table_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='Rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
