# Generated by Django 4.2.15 on 2024-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0002_chatbot_table_is_active_delivery_table_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_table',
            old_name='Instructions',
            new_name='Customer_Name',
        ),
        migrations.RenameField(
            model_name='delivery_table',
            old_name='Recepient_Name',
            new_name='ProductName',
        ),
        migrations.AddField(
            model_name='delivery_table',
            name='Delivery_Date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='delivery_table',
            name='Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
