# Generated by Django 4.2.15 on 2024-11-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0003_rename_instructions_delivery_table_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_table',
            old_name='Location',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='user_table',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_table',
            name='District',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_table',
            name='Pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
