# Generated by Django 4.2.15 on 2024-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0004_rename_location_user_table_address_user_table_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='profileimage',
            field=models.FileField(blank=True, null=True, upload_to='profileimages'),
        ),
    ]
