# Generated by Django 4.2.15 on 2024-11-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0005_user_table_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='User_Profile.user_table')),
            ],
        ),
    ]
